theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 前端开发工程师

# 对你自己的简洁描述
description: 

# 你的美照地址
logo: /assets/images/

# 你的名字
name: 鞠乐

# 你的联系方式
phone: 16621367412

# 你的邮箱
email: kdwsnyg@163.com

# 你目前的住址
address: 吉林省吉林市

# 你毕业院校
school: 合肥工业大学

# 你的专业
profession: 电气工程及其自动化

# 你的学位
degree: 本科

# 你获得过的证书或奖励
credential: 英语四级
